### ISSUE TITLE
Is that coding error？

### ISSUE THREAD

**Issue by OneYoungMean** [SPARK-inc/SPCRJointDynamics#1]
![~R MFYFP8`8C B6ITU)K_FT](https://user-images.githubusercontent.com/44113189/56885072-26369880-6a9e-11e9-813b-9273f02681b1.png)
![TIM截图20190429164541](https://user-images.githubusercontent.com/44113189/56885130-46feee00-6a9e-11e9-8662-0eef3e3fbdaf.png)
![K1UKNA(~OISWAB LKESD(9W](https://user-images.githubusercontent.com/44113189/56885141-4a927500-6a9e-11e9-9d63-250b4c39abe4.png)

**Comment by NoriyukiHiromoto** [comment]
That's right.
Thank you

**Comment by OneYoungMean** [comment]
⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄
![image](https://user-images.githubusercontent.com/44113189/61338331-691d3680-a86b-11e9-8de4-2272e9760b44.png)

BTW I hope it can help you
