### ISSUE TITLE
Error - SPCRJointDynamicsController Does not work through AddComponent Attach to an object

### ISSUE THREAD

**Issue by lingtongmeng** [SPARK-inc/SPCRJointDynamics#11]
My English level is very poor, so the following may be strange....

I want to go to add SPCRJointDynamicsController to attch objects and change some parameters with c #script, but after the Add script came out the Error, SPCRJointDynamics support through c # script to set?

![image](https://user-images.githubusercontent.com/92976894/218094586-51b65a05-95e6-4aa7-a798-e4e7573baead.png)

**Comment by NoriyukiHiromoto** [comment]
We will check for errors.

**Comment by NoriyukiHiromoto** [comment]
Could you try the latest version?

**Comment by lingtongmeng** [comment]
Thank you,I'll try

**Comment by lingtongmeng** [comment]
Sorry, there is another question to ask, can SPCRJointDynamics run on ios and android mobile terminals?

**Comment by NoriyukiHiromoto** [comment]
Works on all platforms supported by Unity.
